import './globals.css'
import { Inter } from 'next/font/google'
import RootProvider from './provider'
import Header from '@/components/common/header'
import Footer from '@/components/common/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      
       <body className={inter.className} style={{ height: '100vh', margin: 0, backgroundColor: 'black' }}>
         <Header/>
         <RootProvider>
          {children}
         </RootProvider>
         <Footer/>
        </body>
        
    </html>
  )
}
